sudo: false

language: node_js

node_js:
  - "6"

env:
  global:
    - NODE_ENV=travisci
    - NPM_CONFIG_PROGRESS="false"

before_install:
  - npm install -g bee-tools bee-tools-test

script:  npm test
